default: &default
    adapter: postgresql
    encoding: unicode

development:
    <<: *default
    database: rails_development

test:
    <<: *default
    database: rails_test

production:
    <<: *default
    database: rails_production
    username: rails
    password: <%= ENV['EXAMPLE_DATABASE_PASSWORD'] %>
  